skip_tags: true
environment:
  coalesce_version: 2.1.0
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NET_CORE_VERSION: netcoreapp2.1
  NPM_TOKEN:
    secure: PpvAZnPCnGvKx69JHFV2FowUIpo0jgV1g1jJpuuPmDyZij9RwMcjuGIAKfsSiaQH

image: Visual Studio 2017
cache: 
  - '%LocalAppData%\NuGet\v3-cache'   # Nuget v3
  - '%LocalAppData%\Yarn\cache'
nuget:
  disable_publish_on_pr: true
platform: Any CPU
before_build:
  - ps: ./build/before_build.ps1
# Broken on appveyor currently - says  The specified framework 'Microsoft.NETCore.App', version '2.0' was not found ???
# cd ..\Coalesce.Domain
# dotnet ef database update --framework netcoreapp2.1
# test: off
build_script:
  - msbuild "C:\projects\coalesce\Coalesce.sln" /p:Configuration=%CONFIGURATION% /p:Platform="%PLATFORM%" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
  - dotnet pack -c %CONFIGURATION% 
artifacts:
  - path: '**\*.nupkg'


for:

# Dev builds - publish to MyGet as "x.x.x-alpha-yyy"
- 
  branches:
    only:
      - dev

  init:
  - ps: >-
      $env:coalesce_version = "$env:coalesce_version-alpha-$env:appveyor_build_number"; 
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        $env:coalesce_version = "$env:coalesce_version-pr-$env:APPVEYOR_PULL_REQUEST_NUMBER"
      }
      Update-AppveyorBuild -Version "$env:coalesce_version"

  configuration: Debug

  deploy:
    provider: NuGet
    server: https://www.myget.org/F/intellitect-coalesce/api/v2/package
    api_key:
      secure: byg3MYXl6/q/Y9tKACVcywkrtdqs4i2ISNSNTDoH/Eg9wz2+CUFHI5ir3zMddwSr
    artifact: /.*\.nupkg/

  after_deploy:
    cmd: cd ./src/coalesce-vue && npm publish --tag dev --access public

# Release candidates - publish to NuGet as "x.x.x-rc-yyy"
- 
  branches:
    only:
      - /release\/.*/

  init:
  - ps: >-
      $env:coalesce_version = "$env:coalesce_version-rc-$env:appveyor_build_number";
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        $env:coalesce_version = "$env:coalesce_version-pr-$env:APPVEYOR_PULL_REQUEST_NUMBER"
      }
      Update-AppveyorBuild -Version "$env:coalesce_version"

  configuration: Release
  
  deploy:
    provider: NuGet
    api_key:
      secure: yMgA4bGdgMlHdlEDUx4P4yPJr5jwDsJlo9s0AW2eQ6y7UjK0N+XUjQ4EyPBcZEGw
    artifact: /.*\.nupkg/

# Releases - publish to NuGet as "x.x.x"
- 
  branches:
    only:
      - master

  init:
  # This one is a bit different from the others - we need to make sure the PR builds are completely unique,
  # and since we aren't appending "-rc-" or "-alpha-" into these versions, we need some other entropy into the version.
  - ps: >-
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        $env:coalesce_version = "$env:coalesce_version-release-pr-$env:APPVEYOR_PULL_REQUEST_NUMBER-$env:appveyor_build_number"
      }
      Update-AppveyorBuild -Version "$env:coalesce_version"

  configuration: Release
  
  deploy:
    provider: NuGet
    api_key:
      secure: yMgA4bGdgMlHdlEDUx4P4yPJr5jwDsJlo9s0AW2eQ6y7UjK0N+XUjQ4EyPBcZEGw
    artifact: /.*\.nupkg/

  after_deploy:
    cmd: cd ./src/coalesce-vue && npm publish --tag latest --access public



