version: 2.0.0-alpha-{build}
branches:
  only:
  - master
  - dev
image: Visual Studio 2017
configuration: Debug
environment:
  nodejs_version: "Current"
cache: 
  - '%LocalAppData%\NuGet\v3-cache'   # Nuget v3
  - '%LocalAppData%\Yarn\cache'
nuget:
  disable_publish_on_pr: true
before_build:
  - cmd: dotnet restore
  - cmd: cd ./src/Coalesce.Web.Vue && yarn
  - cmd: cd ./src/coalesce-vue && yarn && yarn build
  - cmd: yarn add gulp-cli webpack-cli --global
  # Currently, our coalesce scripts for vue is in the knockout web project's gulpfile. 
  # I don't want to add gulp to Coalesce.Web.Vue
  - cmd: cd ./src/Coalesce.Web && gulp coalesce-ko
  - cmd: cd ./src/Coalesce.Web && gulp coalesce-vue
# Broken on appveyor currently - says  The specified framework 'Microsoft.NETCore.App', version '2.0' was not found ???
# cd ..\Coalesce.Domain
# dotnet ef database update --framework netcoreapp2.0
# test: off
build:
  project: Coalesce.sln
  verbosity: minimal
after_build:
  - dotnet pack -c %CONFIGURATION% 
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  server: https://www.myget.org/F/intellitect-coalesce/api/v2/package
  api_key:
    secure: byg3MYXl6/q/Y9tKACVcywkrtdqs4i2ISNSNTDoH/Eg9wz2+CUFHI5ir3zMddwSr
  artifact: /.*\.nupkg/