version: 1.0.{build}
branches:
  only:
  - master
  - 2.0
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
before_build:
- cmd: >-
    nuget restore

    cd src\Coalesce.Web

    npm install

    npm -g install gulp-cli

    gulp coalesce

    cd ..\Coalesce.Domain

    dotnet ef database update
build:
  project: Coalesce.sln
  verbosity: minimal