version: 2.0.0-alpha-{build}
branches:
  only:
  - master
  - 2.0
  - ascott/modular-behaviors
image: Visual Studio 2017
configuration: Debug
cache: 
  - src\Coalesce.Web\node_modules     # local npm modules
  - '%APPDATA%\npm-cache'             # npm cache
  - '%LocalAppData%\NuGet\v3-cache'   # Nuget v3
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dotnet restore

    cd src\Coalesce.Web

    npm install

    npm -g install gulp-cli

    gulp coalesce

    cd ..\Coalesce.Domain

    dotnet ef database update --framework netcoreapp2.0
build:
  project: Coalesce.sln
  verbosity: minimal
after_build:
  - dotnet pack -c %CONFIGURATION% --no-build --include-symbols --output "%APPVEYOR_BUILD_FOLDER%\artifacts"
artifacts:
- path: artifacts\**\*.*
deploy:
  provider: NuGet
  server: https://www.myget.org/F/intellitect-coalesce/api/v2/package
  symbol_server: https://www.myget.org/F/intellitect-coalesce/symbols/api/v2/package
  api_key:
    secure: byg3MYXl6/q/Y9tKACVcywkrtdqs4i2ISNSNTDoH/Eg9wz2+CUFHI5ir3zMddwSr
  skip_symbols: false
  artifact: /.*\.nupkg/